apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rakeshpipelinejsdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rakeshpipelinejsdocker 
    spec:
      containers:
        - name: rakeshpipelinejsdocker 
          image: rakeshcontainerregistry479.azurecr.io/rakeshpipelinejsdocker 
          ports:
          - containerPort: 8080